### ISSUE TITLE
Error when trying to deploy : No module named 'qc_tool'

### ISSUE THREAD

**Issue by Doctor-Who** [eea/copernicus_quality_tools#1]
Hello,

OS Information | openSUSE Leap 15.0
Kernel Version | 4.12.14-lp150.12.45-default
Total CPU | 56
Total memory | 134.8 GB
Docker version | Version | 18.09.1 (API: 1.39)

Trying to deploy this tool with docker compose such as : 
```
version: '3'

services:
  frontend:
    image: eeacms/copernicus-qctool-frontend
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - WORK_DIR=/mnt/qc_tool_volume/work
      - SUBMISSION_DIR=
      - FRONTEND_DB_PATH=/mnt/qc_tool_volume/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work
      - /mnt/tmp/UA2018_QC/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  worker:
    image: eeacms/copernicus-qctool-worker
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_volume/boundaries
      - INCOMING_DIR=/mnt/qc_tool_volume/incoming
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_volume/work
    networks:
      - qc_tool_network
    volumes:
      - /mnt/tmp/UA2018_QC/boundaries:/mnt/qc_tool_boundary/boundaries
      - /mnt/tmp/UA2018_QC/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/tmp/UA2018_QC/work:/mnt/qc_tool_work
      - /mnt/tmp/UA2018_QC/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

volumes:
  qc_tool_volume:
    driver: local

networks:
  qc_tool_network:
    driver: bridge
```

Got error message
> /usr/bin/python3: Error while finding module specification for 'qc_tool.worker.scheduler' (ModuleNotFoundError: No module named 'qc_tool')

Then all container stopped :(
